
services:
  web:
    build: .
    ports:
      - "9010:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    environment:
      MYSQL_HOST=db
      MYSQL_USER=root
      MYSQL_PASSWORD=root
      MYSQL_DATABASE=phpdockerapp
    networks:
      - app-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: phpdockerapp
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
